### ISSUE TITLE
Do I have to convert data to use it ?

### ISSUE THREAD

**Issue by space11** [dictybase-playground/html-to-slatejs#5]
Hi.

Is it required to convert output of html-to-slatejs using `Value.fromJSON( ... )` before I can use it in my editor ?

Thanks.

**Comment by erichartline** [comment]
Yes, in order to use the output in your editor you have to use `Value.fromJSON()`. For our use case, we also had to use `JSON.parse` when getting the data from our API server.

```
this.state = {
     // Initial value of editor
     value: Value.fromJSON(JSON.parse(props.page.content)),
}
```

**Comment by space11** [comment]
Thanks.
